version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cs3219-project-ay2122-2122-s1-g37
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    type:
      - directory
      - file
hooks:
  AfterInstall:
    - location: scripts/install-dependencies.sh
      timeout: 10000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/cleanup.sh
      timeout: 10000
      runas: ec2-user
