name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup node
            uses: actions/setup-node@v2
            with:
              node-version: 16.x
          - name: Install dependencies
            run: npm run install-all
          - name: Cypress tests
            run: npm run cypress-test
          - name: Jest tests
              run: npm run jest-test