name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:5.7
                ports:
                    - 3306/tcp
                env:
                    MYSQL_USER: root
                    MYSQL_PASSWORD: root
                    MYSQL_DATABASE: peerwatch
                    MYSQL_ROOT_PASSWORD: root
                options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
        env:
            LOCAL_DB_HOST: localhost
            LOCAL_DB_USER: root
            LOCAL_DB_PASS: root
            LOCAL_DB_PORT: 3306
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Setup node
            uses: actions/setup-node@v2
            with:
              node-version: 16.x
          - name: Setup Redis
            uses: supercharge/redis-github-action@1.2.0
            with:
                redis-version: 6
          - name: Setup MySQL
            run: |
                mysql -e \. /sql/peerwatch_rooms.sql
                mysql -e \. /sql/peerwatch_users.sql
                mysql -e \. /sql/peerwatch_users_in_rooms.sql
          - name: Install dependencies
            run: npm run install-all
          - name: Cypress tests
            run: npm run cypress-test
          - name: Jest tests
            run: npm run jest-test